const teamColors = {
  "New Jersey Devils": "crimson",
  "New York Islanders": "blue",
  "New York Rangers": "blue",
  "Philadelphia Flyers": "darkorange",
  "Pittsburgh Penguins": "gold",
  "Boston Bruins": "gold",
  "Buffalo Sabres": "navy",
  "Montréal Canadiens": "firebrick",
  "Ottawa Senators": "firebrick",
  "Toronto Maple Leafs": "navy",
  "Carolina Hurricanes": "crimson",
  "Florida Panthers": "crimson",
  "Tampa Bay Lightning": "mediumblue",
  "Washington Capitals": "firebrick",
  "Chicago Blackhawks": "firebrick",
  "Detroit Red Wings": "crimson",
  "Nashville Predators": "gold",
  "St. Louis Blues": "navy",
  "Calgary Flames": "crimson",
  "Colorado Avalanche": "darkred",
  "Edmonton Oilers": "darkorange",
  "Vancouver Canucks": "mediumblue",
  "Anaheim Ducks": "darkorange",
  "Dallas Stars": "green",
  "Los Angeles Kings": "#1B1212",
  "San Jose Sharks": "teal",
  "Columbus Blue Jackets": "darkblue",
  "Minnesota Wild": "darkgreen",
  "Winnipeg Jets": "navy",
  "Arizona Coyotes": "darkred",
  "Vegas Golden Knights": "burlywood",
  "Seattle Kraken": "#00D1D1",
};

export default teamColors;
